// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7U3t3u0xXKi8D791_QslwiIli9ghOuQ',
    appId: '1:567565960548:web:897ec0ced49cbfb1a9e671',
    messagingSenderId: '567565960548',
    projectId: 'spotify077',
    authDomain: 'spotify077.firebaseapp.com',
    storageBucket: 'spotify077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqsWoH2mkmHPKFGFlUAi2LeBlhRc-F_8c',
    appId: '1:567565960548:android:66df7cb6a6d9d0f6a9e671',
    messagingSenderId: '567565960548',
    projectId: 'spotify077',
    storageBucket: 'spotify077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpLMnu2lvNcWQKAPl0uM3BTDEeIZ2Exc',
    appId: '1:567565960548:ios:ea9b72c89b13705ea9e671',
    messagingSenderId: '567565960548',
    projectId: 'spotify077',
    storageBucket: 'spotify077.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcpLMnu2lvNcWQKAPl0uM3BTDEeIZ2Exc',
    appId: '1:567565960548:ios:ea9b72c89b13705ea9e671',
    messagingSenderId: '567565960548',
    projectId: 'spotify077',
    storageBucket: 'spotify077.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl7U3t3u0xXKi8D791_QslwiIli9ghOuQ',
    appId: '1:567565960548:web:adf0d7653ecedfe3a9e671',
    messagingSenderId: '567565960548',
    projectId: 'spotify077',
    authDomain: 'spotify077.firebaseapp.com',
    storageBucket: 'spotify077.appspot.com',
  );
}
